[package]
name = "openapi"
version = "0.1.0"
authors = ["softprops <d.tangren@gmail.com>"]
build = "build.rs"

[build-dependencies]
serde_codegen = "0.8"
glob = "0.2.11"

[dependencies]
serde = "0.8"
serde_json = "0.8"
serde_yaml = "0.5"
