[package]
name = "openapi"
version = "0.1.0"
authors = ["softprops <d.tangren@gmail.com>"]

[dependencies]
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
serde_yaml = "0.7"
error-chain = "0.10"
